### PR TITLE
change TEXTGENUI in .env to TEXTGENWUI for consistency

### PR DESCRIPTION
**Pull request by Butterroach**
useless pr maybe but consistency so merge pls!!!!!

### CODE REVIEW

**Comment by Butterroach** [comment]
i dominate this repo's pull requests

**Comment by artifishvr** [comment]
> i dominate this repo's pull requests

how about you dominate me

**Comment by Butterroach** [comment]
At least 1 approving review is required by reviewers with write access. Learn more about pull request reviews.

**Review by artifishvr — COMMENTED** [review]
god

**Review by artifishvr — APPROVED** [review]
its good

**Pull request merged**
